"""add_country_to_profile

Revision ID: e5e6f49ec61a
Revises: 186b057085f3
Create Date: 2026-01-17 13:56:06.845251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e5e6f49ec61a'
down_revision: Union[str, Sequence[str], None] = '186b057085f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('profile', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_profile_slug'), 'profile', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_slug'), table_name='profile')
    op.drop_column('profile', 'slug')
    op.drop_column('profile', 'country')
    # ### end Alembic commands ###
